version: '3.9'

services:
  spring:
    image: search-backend
    container_name: search-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - homesweet-network
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch_exporter
    restart: always
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://13.124.109.204:9200'
      - '--es.all'
    networks:
      - homesweet-network

networks:
  homesweet-network:
    driver: bridge