global:
  scrape_interval: 5s

scrape_configs:
  # ============================
  # EC2 spring boot prometheus
  # ============================
  - job_name: 'ec2-spring-boot'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['3.35.228.233:8080']

  # ============================
  # EC2 node exporter
  # ============================
  - job_name: 'ec2-node-exporter'
    static_configs:
      - targets: ['3.35.228.233:9100']

  # ============================
  # EC2 mysqld exporter
  # ============================
  - job_name: 'ec2-mysql-exporter'
    static_configs:
      - targets: ['3.35.228.233:9104']

  # ============================
  # Local Docker exporters (optional)
  # ============================
  - job_name: 'local-node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']