server:
  port: 8080

spring:
  application:
    name: homesweet-back
  config:
    import: optional:file:.env[.properties]
  elasticsearch:
    uris: http://3.36.60.169:9200

logging:
  level:
    root: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: homesweet-back
  prometheus:
    metrics:
      export:
        enabled: true