server:
  port: 8080

spring:
  application:
    name: homesweet-back
  config:
    import: optional:file:.env[.properties]
  elasticsearch:
    uris: ${ELASTIC_URL}
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
      password:
      timeout: 2000ms
  cache:
    type: redis

logging:
  level:
    root: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: homesweet-back
  prometheus:
    metrics:
      export:
        enabled: true